fruits={"apple","orange","strawberry","pineapple"}
company={"google","microsoft","apple"}
print(fruits)
print(company)
fruits.intersection_update(company)
print(fruits)
##################################################
x={"apple","orange","strawberry","pineapple"}
y={"google","microsoft","apple"}
z=x.intersection(y)
print(z)
###################################################
a={"apple","orange","strawberry","pineapple"}
b={"google","microsoft","apple"}
c=a.symmetric_difference(b)
print(c)
###################################################
d={"apple","orange","strawberry","pineapple"}
e={"google","microsoft","apple"}
d.symmetric_difference_update(e)
print(d)
